version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root